# Generated by Django 4.1.7 on 2023-03-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vital_signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('respiratory', models.IntegerField()),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('pre_consultion_action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Middle_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[{'Male', 'M'}, {'F', 'Female'}], max_length=255)),
                ('marital_status', models.CharField(choices=[{'Single', 'single'}, {'Married', 'married'}, {'Divorced', 'divorced'}], max_length=255)),
                ('next_of_kin', models.CharField(max_length=255)),
                ('next_of_kin_phone_number', models.CharField(max_length=255)),
                ('vital_signs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.vital_signs')),
                ('doctor_assigned', models.ManyToManyField(to='management.doctor')),
                ('drug_administered', models.ManyToManyField(to='management.drug')),
            ],
        ),
    ]
