# Generated by Django 4.1.7 on 2023-03-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_vital_signs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital_signs',
            name='date',
        ),
    ]
